#!/bin/bash
echo resizing
mogrify -resize 968x648 /home/pi/photobooth/images/*.jpg
echo Montage making
montage /home/pi/photobooth/images/*.jpg -tile 2x2 -geometry +30+30 -texture /home/pi/photobooth/media/backgroundg.jpg /home/pi/photobooth/images/temp_montage2.jpg
echo adding overlay
composite -gravity center /home/pi/photobooth/media/overlay.png /home/pi/photobooth/images/temp_montage2.jpg /home/pi/photobooth/images/temp_montage3.jpg
suffix=$(date +%F_%T)
echo Saving montage
cp /home/pi/photobooth/images/temp_montage3.jpg /home/pi/photobooth/archive/${suffix}.jpg
cp /home/pi/photobooth/images/temp_montage3.jpg /home/pi/photobooth/archive/photobooth.jpg
#lp -d Canon_CP900 /home/pi/photobooth/archive/photobooth.jpg
echo cleaning up
rm /home/pi/photobooth/images/*.jpg

